# Generated by Django 3.0.7 on 2022-06-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('live_link', models.URLField()),
                ('code_link', models.URLField()),
                ('preview_img', models.URLField()),
                ('type', models.CharField(choices=[('TUT', 'Tutorial'), ('COU', 'Graded Coursework'), ('IND', 'Individual Project'), ('COM', 'Commission')], default='IND', max_length=3)),
                ('description', models.TextField()),
                ('description_nl', models.TextField(default='Beschrijving binnenkort beschikbaar!')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_languages', to='codeprojects.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_languages', to='codeprojects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='projects', through='codeprojects.ProjectLanguage', to='codeprojects.Language'),
        ),
        migrations.AddConstraint(
            model_name='projectlanguage',
            constraint=models.UniqueConstraint(fields=('project', 'language'), name='unique_pairing'),
        ),
    ]
